start cmd /k dotnet run --project ./ConsoleProj1
start cmd /k dotnet run --project ./ConsoleProj2
start cmd /k dotnet run --project ./ConsoleProj3
start cmd /k dotnet run --project ./ConsoleProj4
start cmd /k dotnet run --project ./ConsoleProj5
start cmd /k dotnet run --project ./ConsoleProj6
start cmd /k dotnet run --project ./ConsoleProj7
start cmd /k dotnet run --project ./ConsoleProj8
start cmd /k dotnet run --project ./ConsoleProj9
start cmd /k dotnet run --project ./ConsoleProj10
